apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-03-16T10:53:32Z"
  generation: 1
  labels:
    run: madrid
  name: madrid
  namespace: default
  resourceVersion: "3039"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/madrid
  uid: bd9abd58-47d9-11e9-ae3c-42010aa40fc2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: madrid
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: madrid
    spec:
      containers:
        - image: gcr.io/gdccmadrid-kevin/gcdcmadrid-kevin:570f10fceb0f7db610b0ba632664fd139e7d7163
          imagePullPolicy: IfNotPresent
          name: madrid
          ports:
            - containerPort: 9000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
